services:
  app:
    image: gestion-bares-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/tapatech
      - DATABASE_USERNAME=migue
      - DATABASE_PASSWORD=migue
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

  mysqldb:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: tapatech
      MYSQL_USER: migue
      MYSQL_PASSWORD: migue
      MYSQL_ROOT_PASSWORD: 112112-@bE3z
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p112112-@bE3z"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - internal

volumes:
  mysql-data:

networks:
  internal:
    driver: bridge
