version: '3.9'
services:
  app:
    container_name: tapatech-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://tapatech-bd:3306/tapatech
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    container_name: tapatech-bd
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tapatech
      MYSQL_USER: migue
      MYSQL_PASSWORD: migue
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:
    external: false
